### ISSUE TITLE
Run-time payload registration

### ISSUE THREAD

**Issue by ncc-iz** [nccgroup/depthcharge#23]
Currently, only built-in payloads can be used with `Depthcharge.execute_payload`. Need to provide a way to register custom user payloads at runtime.

**Comment by jynik** [comment]
Marked as bug. This is something I should have addressed prior to the release and it fell through the cracks.

Scheduled for inclusion in v0.2.0

**Comment by jynik** [comment]
Fix staged in `next` @ 0ffb75fafc7ae8a7a338db1b9290415b5a67f3b6.

**Comment by jynik** [comment]
0ffb75fafc7ae8a7a338db1b9290415b5a67f3b6 isn't correct. `self._payload` should be `self._payloads`

**Comment by jynik** [comment]
Fix staged in`next` @ b95cd76adc0563cfb88cfc5bcd0aea1805cc480b.
