### ISSUE TITLE
Depthcharge `deploy_payload` should flush icache

### ISSUE THREAD

**Issue by ncc-iz** [nccgroup/depthcharge#24]
Currently, icache is not being cleaned. As a result, when recompiling the payload and redeploying, erratic behavior is observed (e.g. payload randomly crashing or returning error code). In order to work around this, icache could be disabled with U-Boot command `icache off` when available; ideally Depthcharge should clean dcache followed by flushing icache whenever deploying payloads.

See https://community.arm.com/developer/ip-products/processors/b/processors-ip-blog/posts/caches-and-self-modifying-code

**Comment by jynik** [comment]
Confirmed as bug, per offline discussion.

**Comment by jynik** [comment]
Fix staged in `next` @ c68a29ade03e9852c9e2b074ee3b123c143517f4.
