### ISSUE TITLE
depthcharge-read-mem -a argument is required conflicting with docs

### ISSUE THREAD

**Issue by ncc-iz** [nccgroup/depthcharge#25]
The documentation (`depthcharge-read-mem --help`) claims that:

```
  -a <value>, --address <value>
                        Target address to read from Default: 0x00000000
```

However, running `depthcharge-read-mem` without providing the `-a` option results in the following error:

```
depthcharge-read-mem: error: the following arguments are required: -a/--address
```

**Comment by jynik** [comment]
Confirmed as bug.  depthcharge-read-mem should use invoke `cmdline.add_addr_arg()` with `default=None`.

**Comment by jynik** [comment]
Staged in `next` @ 14c09998833b663a25343bd0b077ebaab368b060
