### ISSUE TITLE
Documentation: 404 URL in introduction.rst

### ISSUE THREAD

**Issue by youssefms** [nccgroup/depthcharge#76]
**Affected Document(s)**

introduction.rst

**Description of Issue**

The following link in line 87 of the introduction.rst document is returning a 404 Page not found. 
.. _NXP's HABv4: https://www.nxp.com/docs/en/application-note/AN4581.pdf

**Comment by jynik** [comment]
Argh NXP! Looks like they've decided to force folks to log (with a free account) in to view this document now.

The "proper" download link to the document is here: `https://www.nxp.com/webapp/Download?colCode=AN4581`

And one can search for it as shown here: `https://www.nxp.com/search?keyword=AN4581%20i.MX%20Secure%20Boot&category=documents&start=0&filter=type%3E%3EApplication%20Note`

It frustrates me that there's no document landing page that presents just an abstract.  I would prefer not to link to something that just asks for a login, but fear that the search results is a fraglie way to lead folks to see a summary of what they're about to download before logging in.

**Comment by jynik** [comment]
Fix stated in `next` @ 3fba01c76eecae4f57c086f7ae9e946ec85f1c7e
