### ISSUE TITLE
-R Flag fails when running "MdCrashRegisterReader"

### ISSUE THREAD

**Issue by youssefms** [nccgroup/depthcharge#77]
Encountered the following error while running command "inspect depthcharge-inspect --arch arm -A -R -c test.cfg  -m term":

Error: No data abort content found in the following text:
00000001: 80ea0000                               ....

The last part in the term output is the following:

Early malloc usage: 464 / 2000
fdt_blob    = 0x3af69fb0
U-Boot> md.l 1 1
00000001: 80ea0000                               ....
U-Boot> 03<INTERRUPT>
U-Boot> 

**Depthcharge Version**

Depthcharge Release 0.2.0 (main branch) 

**Target System**

Device: Raspberry Pi 4 Model B
SOC: bcm283x
U-Boot: 2020.01 (Jan 06 2020 - 20:56:31 +0000)

**Logs**

See console log attached
[console.log](https://github.com/nccgroup/depthcharge/files/6603564/console.log)

**Comment by jynik** [comment]
Thanks. I was able to reproduce this on an AARCH64 target as well.

On my particular target, I was able to induce a crash via `md.l 0xffffffff 4`, but we confirmed out-of-band that this wasn't working for you.

Where did you see "SetexprCrashRegisterReader" by the way?  The failure we've been discussing has been using `md.l` -- I'm curious if there's a second bug here.

**Comment by jynik** [comment]
This issue results from using -R on an AARCH64 target while using Depthcharge in ARM 32-bit mode.

As such, I'm going to close this issue and a comment to #3 accordingly, as the AARCH64 implementation will need to invoke a data abort by some other means.

**Comment by jynik** [comment]
Further notes regarding this issue are being collected in #3.
